routes/web.php
<?php

/**
 * Utilities
 */
Route::get('/img/thumb', 'UtilitiesController@imageThumb');
Route::get('/downloadFile', 'UtilitiesController@downloadFile');

/*Route::get('/phpinfo', function() {
    return phpinfo();
});*/

Route::get('/clearCache', 'PageController@clearCache')->name('clearCache');



/* START: Sitemap */

Route::get('/sitemap.xml', 'SitemapController@index');
/*Route::get('/sitemap/pages.xml', 'SitemapController@pages');
Route::get('/sitemap/events.xml', 'SitemapController@events');
Route::get('/sitemap/blog.xml', 'SitemapController@blog');*/

/* END: Sitemap */


/*
 *  Set up locale if other language is selected
 */

$localPrefix = '';
if (in_array(Request::segment(1), config('translatable.locales'))) {
    App::setLocale(Request::segment(1));
    \Carbon\Carbon::setLocale(Request::segment(1));
    setlocale(LC_TIME, Request::segment(1));
    $localPrefix = Request::segment(1);
}


Route::group(['prefix' => $localPrefix], function () {

    Route::post('/book/course/{id}/{slug}', ['as'=>'bookCourse', 'uses' => 'BookingController@bookCourse']);
    Route::post('/book/event/{id}/{slug}', ['as'=>'bookEvent', 'uses' => 'BookingController@bookEvent']);
    Route::post('/contact', ['as'=>'submitContact', 'uses' => 'ContactController@submitContact']);
    Route::post('/your-career-guidance-hero', ['as'=>'submitContactForm', 'uses' => 'ContactController@submitContactForm']);
    Route::post('/subscribeNewsletter', ['as'=>'subscribeNewsletter', 'uses' => 'NewsletterController@subscribe']);
    Route::get('/search', ['as'=>'search', 'uses' => 'SearchController@search']);
});


/* Auth is used for CMS only. Website has no user accounts*/

Auth::routes();
Route::any('register', function () {
    abort(404);
});
Route::get('logout', ['as' =>'logout', 'uses' => 'Auth\LoginController@logout']);

/* Start : CMS Routes */

Route::get('admin', function () {
    return redirect()->route('cms.login');
});

Route::group(['prefix' => 'cms'], function () {
    
    Route::get('/', function () {
        return redirect()->route('cms.login');
    });
    Route::get('login', ['as' => 'cms.login', 'uses' => 'Auth\LoginController@showLoginForm']);

    Route::group(['namespace' => 'CMS', 'middleware' => 'auth.cms'], function () {


        /**
         * Misc CMS actions
         */
        Route::get('dashboard', ['as'=>'cms.dashboard', 'uses' => 'MainController@dashboard']);
        Route::get('setlocale/{locale}', ['as'=>'cms.setlocale', 'uses' =>  'MainController@setLocale']);


        /**
         * Profile
         */
        Route::get('profile', ['as'=>'cms.profile.edit', 'uses' =>  'ProfileController@edit']);
        Route::post('profile', ['as'=>'cms.profile.update', 'uses' =>  'ProfileController@update']);

        /**
         * Settings
         */
        Route::get('settings', ['as'=>'cms.settings.edit', 'uses' =>  'SettingsController@edit']);
        Route::post('settings', ['as'=>'cms.settings.update', 'uses' =>  'SettingsController@update']);

        /**
         * Users
         */
        Route::resource('users', 'UsersController', ['except' => ['show', 'destroy'], 'as' => 'cms']);
        Route::get('users/{users}/destroy', ['as' => 'cms.users.destroy', 'uses' => 'UsersController@destroy']);

        /**
         * Pages
         */
        //Route::get('pages/{pages}/confirm', ['as' => 'cms.pages.confirm', 'uses' => 'PagesController@confirm']);
        Route::resource('pages', 'PagesController', ['except' => ['show', 'destroy'], 'as' => 'cms']);
        Route::get('pages/{pages}/destroy', ['as' => 'cms.pages.destroy', 'uses' => 'PagesController@destroy']);

        /**
         * Logo Slider
         */
        Route::resource('logoSliders', 'LogoSlidersController', ['except' => ['show', 'destroy'], 'as' => 'cms']);
        Route::get('logoSliders/{logoSliders}/destroy', ['as' => 'cms.logoSliders.destroy', 'uses' => 'LogoSlidersController@destroy']);
        Route::post('logoSliders/sort', ['as' => 'cms.logoSliders.sort', 'uses' => 'LogoSlidersController@sort']);
        Route::get('logoSliders/{logoSliders}/tinify', ['as' => 'cms.logoSliders.tinify', 'uses' => 'LogoSlidersController@tinifyImage']);

        /**
         * Media
         */
        Route::resource('media', 'MediaController', ['as' => 'cms']);
        Route::get('media/{media}/destroy', ['as' => 'cms.media.destroy', 'uses' => 'MediaController@destroy']);
        Route::get('media/{media}/tinify', ['as' => 'cms.media.tinify', 'uses' => 'MediaController@tinifyImage']);

        /**
         * Mediable
         */
        Route::get('{mediableType}/{mediableId}/media', ['as' => 'cms.mediable.show', 'uses' => 'MediableController@show']);
        Route::post('{mediableType}/{mediableId}/update', ['as' => 'cms.mediable.update', 'uses' => 'MediableController@update']);
        Route::get('{mediableType}/{mediableId}/media/select', ['as' => 'cms.mediable.select', 'uses' => 'MediableController@select']);
        Route::post('{mediableType}/{mediableId}/media/attach', ['as' => 'cms.mediable.attach', 'uses' => 'MediableController@attach']);


        /**
         * BLog
         */
        Route::resource('blog', 'BlogController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('blog/{blog}/destroy', ['as' => 'cms.blog.destroy', 'uses' => 'BlogController@destroy']);

        /**
         * Blog Categories
         */
        Route::resource('blogCategories', 'BlogCategoriesController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('blogCategories/{blogCategories}/destroy', ['as' => 'cms.blogCategories.destroy', 'uses' => 'BlogCategoriesController@destroy']);

        /**
         * Events
         */
        Route::resource('events', 'EventsController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('events/{events}/destroy', ['as' => 'cms.events.destroy', 'uses' => 'EventsController@destroy']);
        Route::get('events/{events}/tinify', ['as' => 'cms.events.tinify', 'uses' => 'EventsController@tinifyImage']);

        /**
         * Courses
         */
        Route::resource('courses', 'CoursesController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('courses/{events}/destroy', ['as' => 'cms.courses.destroy', 'uses' => 'CoursesController@destroy']);
        Route::post('courses/sort', ['as' => 'cms.courses.sort', 'uses' => 'CoursesController@sort']);
        Route::get('courses/{courses}/tinify', ['as' => 'cms.courses.tinify', 'uses' => 'CoursesController@tinifyImage']);

        /**
         * Clients
         */
        Route::resource('clients', 'ClientsController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('clients/{clients}/destroy', ['as' => 'cms.clients.destroy', 'uses' => 'ClientsController@destroy']);
        Route::post('clients/sort', ['as' => 'cms.clients.sort', 'uses' => 'ClientsController@sort']);
        Route::get('clients/{clients}/tinify', ['as' => 'cms.clients.tinify', 'uses' => 'ClientsController@tinifyImage']);

        /**
         * Awards
         */
        Route::resource('awards', 'AwardsController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('awards/{awards}/destroy', ['as' => 'cms.awards.destroy', 'uses' => 'AwardsController@destroy']);
        Route::post('awards/sort', ['as' => 'cms.awards.sort', 'uses' => 'AwardsController@sort']);
        Route::get('awards/{awards}/tinify', ['as' => 'cms.awards.tinify', 'uses' => 'AwardsController@tinifyImage']);

        /**
         * Testimonials
         */
        Route::resource('testimonials', 'TestimonialsController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('testimonials/{testimonials}/destroy', ['as' => 'cms.testimonials.destroy', 'uses' => 'TestimonialsController@destroy']);
        Route::post('testimonials/sort', ['as' => 'cms.testimonials.sort', 'uses' => 'TestimonialsController@sort']);
        Route::get('testimonials/{testimonials}/tinify', ['as' => 'cms.testimonials.tinify', 'uses' => 'TestimonialsController@tinifyImage']);

        /**
         * Careers
         */
        Route::resource('careers', 'CareersController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('careers/{careers}/destroy', ['as' => 'cms.careers.destroy', 'uses' => 'CareersController@destroy']);

        /**
         * Locations
         */
        Route::resource('locations', 'LocationsController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('locations/{locations}/destroy', ['as' => 'cms.locations.destroy', 'uses' => 'LocationsController@destroy']);
        Route::post('locations/sort', ['as' => 'cms.locations.sort', 'uses' => 'LocationsController@sort']);
        Route::get('locations/{locations}/tinify', ['as' => 'cms.locations.tinify', 'uses' => 'LocationsController@tinifyImage']);

        /**
         * Casestudies Categories
         */
        Route::resource('casestudyCategories', 'CasestudyCategoriesController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('casestudyCategories/{casestudyCategories}/destroy', ['as' => 'cms.casestudyCategories.destroy', 'uses' => 'CasestudyCategoriesController@destroy']);
        /**
         * Casestudies Sectors
         */
        Route::resource('casestudySectors', 'CasestudySectorsController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('casestudySectors/{casestudySectors}/destroy', ['as' => 'cms.casestudySectors.destroy', 'uses' => 'CasestudySectorsController@destroy']);
        /**
         * Casestudies
         */
        Route::resource('casestudies', 'CasestudiesController', ['except'=>['show', 'destroy'], 'as' => 'cms']);
        Route::get('casestudies/{casestudies}/destroy', ['as' => 'cms.casestudies.destroy', 'uses' => 'CasestudiesController@destroy']);

        /**
         * Team
         */

app/Http/Controllers/CMS/AwardsController.php
<?php

namespace App\Http\Controllers\CMS;

use Illuminate\Support\Str;
use File;
use Image;
use App\Award;
use App\Http\Requests;
use App\Utilities\Search;
use Illuminate\Http\Request;
use Baum\MoveNotPossibleException;

class AwardsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $awards = Award::orderBy('lft', 'asc')->get();

        return view('cms.awards.index', compact('awards'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Award $award)
    {
        $orderItems = Award::orderBy('lft', 'asc')->get();

        return view('cms.awards.form', compact('award', 'orderItems'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\StoreAwardRequest $request)
    {
        $award = Award::create($request->only('name', 'status') + ['created_by' => $this->admin->id]);

        $this->updateOrder($award, $request);

        /**
         * Save Translation
         */
        $award->saveTranslation($request->only('title', 'content'));

        if ($request->hasFile('logo')) {
            $award->saveLogo($request->file('logo'));
        }

        flash()->success('Award has been created.');

        return redirect()->route('cms.awards.index');

        /**
         * Update Search Index
         */
        $this->updateSearchIndex(['id' => $award->id] + $request->only('name', 'title', 'content', 'status'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $award = Award::findOrFail($id);

        $orderItems = Award::orderBy('lft', 'asc')->get();

        return view('cms.awards.form', compact('award', 'orderItems'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\UpdateAwardRequest $request, $id)
    {
        $award = Award::findOrFail($id);

        if ($response = $this->updateOrder($award, $request)) {
            return $response;
        }

        $award->fill($request->only('name', 'status') + ['updated_by'=>$this->admin->id])
            ->save();

        /**
         * Save Translation
         */
        $award->saveTranslation($request->only('title', 'content'));

        if ($request->hasFile('logo')) {
            $award->saveLogo($request->file('logo'));
        }

        flash()->success('Award has been updated.');

        return redirect()->route('cms.awards.index');

        /**
         * Update Search Index
         */
        $this->updateSearchIndex(['id' => $award->id] + $request->only('name', 'title', 'content', 'status'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $award = Award::findOrFail($id);

        File::delete($award->logo);
        $award->deleteThumbs();

        $award->delete();

        flash()->success('Award has been deleted.');

        return back();
    }

    public function sort(Requests\UpdateOrderingRequest $request)
    {

        $ids = explode("|", $request->input('ids'));
        $awards = [];

        for ($i=0; $i<count($ids); $i++) {
            $id = $ids[$i];
            $awards[$id] = Award::findOrFail($id);
            if ($i>0) {
                try {
                    $awards[$id]->moveToRightOf($awards[$ids[$i-1]]);
                } catch (MoveNotPossibleException $e) {
                    return redirect(route('cms.awards.index'))->withErrors([
                        'error' => 'Cannot make an item a child of itself.'
                    ]);
                }
            }
        }

        flash()->success('Order has been saved.');

        return redirect(route('cms.awards.index'));
    }

    protected function updateOrder(Award $award, Request $request)
    {
        if ($request->has('order', 'orderItem')) {
            try {
                $award->updateOrder($request->input('order'), $request->input('orderItem'));
            } catch (MoveNotPossibleException $e) {
                return redirect(route('cms.awards.edit', $award->id))->withInput()->withErrors([
                    'error' => 'Cannot make an item a child of itself.'
                ]);
            }
        }
    }

    protected function updateSearchIndex($item)
    {

        if ($item['status']) {
            Search::addOrUpdateItem('awards', $item['id'], $item['title'], $item['content'], route('awards') . '#' . Str::slug($item['name']));
        } else {
            Search::deleteItem('awards', $item['id']);
        }
    }

    public function tinifyImage($id)
    {
        $item = Award::findOrFail($id);
        $imageColumnName = $item->getImageColumnName();
        $imageTinifiedColumnName = $imageColumnName . '_tinified';

        if (File::isFile($item->{$imageColumnName})) {
            $item->deleteThumbs();

            $code = tinifyImage($item->{$imageColumnName});

            if ($code == 'tinified') {
                flash()->success('Image has been tinified.');

                $item->{$imageTinifiedColumnName} = '1';
                $item->save();
            } else if ($code == 'apiError') {
                flash()->success('Your API key is not valid, or your monthly limit is exhausted.');
            } else {
                flash()->success('Unknown error, Please try again.');
            }
        } else {
            flash()->success('Nothing to tinify.');
        }

        return redirect()->back();
    }
}

app/Http/Controllers/CMS/Controller.php
<?php

namespace App\Http\Controllers\CMS;

use App;
use Auth;
use Session;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{

    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    protected $admin;
    protected $locale;
    protected $locales;

    public function __construct()
    {
        // Share locales
        $locales = config('cms.locales');
        $this->locales = $locales;
        view()->share('locales', $this->locales);
    
    
        $this->middleware(function ($request, $next) {
        
            view()->share('signedIn', Auth::check());
        
            $this->admin = Auth::user();
            view()->share('admin', $this->admin);
            
            $this->locale = Session::get('locale', config('app.fallback_locale'));
            App::setLocale($this->locale);
            view()->share('locale', $this->locale);
        
            return $next($request);
        });
    }
}

app/Http/Controllers/CMS/MainController.php
<?php

namespace App\Http\Controllers\CMS;

use App;
use Session;
use App\Http\Requests;
use Illuminate\Http\Request;

class MainController extends Controller
{

    public function dashboard()
    {

        return view('cms.main.dashboard');
    }

    public function setLocale($locale)
    {

        Session::put('locale', $locale);
        App::setLocale($locale);

        return redirect()->route('cms.dashboard');
    }
}

resources/views/cms/blog/_tier.blade.php
<div class="tier clearfix" id="tier-{{ is_int($key) ? $key+1 : $key }}">
    <div class="col-md-5">
        @if(isset($field))
            <input type="hidden" name="field_id_{{ $key }}" value="{{ $field->id }}"/>
        @endif
        <input type="text"
               class="form-control"
               id="field-name-{{ $key }}"
               name="field_name[]"
               placeholder="Name"
               value="{{ old('field_name.'.$key, (isset($field->name) && is_int($key))?$field->name:'') }}">
    </div>
    <div class="col-md-5">
        <input type="text"
               class="form-control translation-field"
               id="field-value-{{ $key }}"
               name="field_value[]"
               placeholder="Value"
               value="{{ old('field_value.'.$key, (isset($field->value) && is_int($key))?$field->value:'') }}">
    </div>
    @if(is_int($key) && $key == 0)
        <div class="col-md-2">
            <a href="#" id="add-custom-field-tier" class="btn btn-info"><span
                        class="glyphicon glyphicon-plus"></span></a>
        </div>
    @elseif (!is_int($key) || $key > 0)
        <div class="col-md-2">
            <a href="#" class="btn btn-danger remove-tier"><span
                        class="glyphicon glyphicon-remove"></span></a>
        </div>
    @endif
</div>

resources/views/cms/blog/form.blade.php
@extends('cms.layouts.default')

@section('title', $post->exists ? 'Edit Post : '.$post->title : 'Create New Post')


@section('heading')

    <div class="row heading">
        <div class="col-md-12">
            <h3>@yield('title')</h3>
        </div>
    </div>

@stop

@section('content')

    <form action="{{$post->exists ? route('cms.blog.update', $post->id) : route('cms.blog.store')}}"
          method="post">


        @if($post->exists)
            <input type="hidden" name="_method" value="PUT">
        @endif

        {{ csrf_field() }}

        <div>

            <!-- Nav tabs -->
            <ul class="nav nav-tabs form-tablist" role="tablist">
                <li role="presentation" class="active"><a href="#content-container" aria-controls="content-container"
                                                          role="tab" data-toggle="tab">Content</a></li>
                <li role="presentation"><a href="#meta-container" aria-controls="meta-container" role="tab"
                                           data-toggle="tab">Meta</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">

                <div role="tabpanel" class="tab-pane active" id="content-container">
                    <div class="form-group">
                        <label for="name">Name </label>
                        <input type="text"
                               class="form-control {{ $post->exists ? '':'make-slug' }}"
                               id="name"
                               name="name"
                               placeholder="Name"
                               value="{{ old('name', $post->name) }}"
                               required>
                    </div>

                    <div class="form-group">
                        <label for="slug">Slug
                        </label>

                        <input type="text"
                               class="form-control name-slug"
                               id="slug"
                               name="slug"
                               placeholder="Slug"
                               value="{{ old('slug', $post->slug) }}"
                               required>
                    </div>

                    <div class="form-group">
                        <label for="title">Title </label>
                        <input type="text"
                               class="form-control translation-field"
                               id="title"
                               name="title"
                               placeholder="Title"
                               value="{{ old('title', $post->title) }}"
                               required>
                    </div>

                    <div class="form-group">
                        <label for="banner_text">Banner Text </label>
                        <input type="text"
                               class="form-control translation-field"
                               id="banner_text"
                               name="banner_text"
                               placeholder="Banner Text"
                               value="{{ old('banner_text', $post->banner_text) }}"
                               >
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="published-at">Published At</label>
                        </div>
                        <div class="col-md-5">
                            <input type="datetime"
                                   class="form-control datetimepicker"
                                   id="published-at"
                                   name="published_at"
                                   placeholder="Published At"
                                   value="{{ old('published_at', $post->published_at?:date('Y-m-d') ) }}"
                                   required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label>Categories</label>
                        <div class="checkbox checkboxes">
                            @foreach($categories as $category)
                                <label>
                                    <input type="checkbox" name="categories[]" value="{{ $category->id }}"
                                    {{ in_array($category->id, $post->categories->pluck('id')->toArray())?"checked":"" }}
                                    />
                                    {{ $category->title }}
                                </label>
                            @endforeach
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-body">
                            <label>Custom Fields</label>
                            <br/>
                            <br/>
                            <div class="tiers" id="custom-field-tiers" data-tier-container="#custom-field-tiers"
                                 data-tier-source="#custom-field-tier-source" data-add-tier-trigger="#add-custom-field-tier"
                                 data-tier-id-count="{{ count($post->customFields)?:1 }}">
                                @forelse($post->customFields as $key => $field)
                                    @include('cms.blog._tier', ['key' => $key, 'field' => $field])
                                @empty
                                    @include('cms.blog._tier', ['key' => 0, 'field' => null])
                                @endforelse
                            </div>

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="name">Content </label>

                        <div class="editor translation-field round-edges">
                            <textarea class="tinymce-editor form-control" name="content" id="content"
                                      rows="10">{{ old('content', $post->content) }}</textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="author_id">
                            Author
                        </label>
                        <select id="author_id"
                                name="author_id"
                                class="form-control">
                            @foreach($users as $user)
                                <option value="{{ $user->id }}" {{ old('author_id', $post->author_id?:$admin->id) == $user->id ? 'selected':'' }}>
                                    {{ $user->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>


                    <div class="form-group">
                        <label for="status">
                            Status
                        </label>
                        <select id="status"
                                name="status"
                                class="form-control">
                            <option value="0" {{ old('status', $post->status) == "0" ? 'selected':'' }}>Inactive
                            </option>
                            <option value="1" {{ old('status', $post->status) == "1" ? 'selected':'' }}>Active</option>
                        </select>
                    </div>
                </div>

                <div role="tabpanel" class="tab-pane" id="meta-container">
                    <div class="form-group">
                        <label for="title">Meta Title </label>
                        <input type="text"
                               class="form-control translation-field"
                               id="meta_title"
                               name="meta_title"
                               placeholder="Meta Title"
                               value="{{ old('meta_title', $post->meta_title) }}"
                        >
                    </div>

                    <div class="form-group">
                        <label for="name">Meta Keywords </label>

                        <div class="editor">
                            <textarea class="form-control  translation-field" name="meta_keywords" id="meta_keywords" rows="3"
                                      placeholder="Meta Keywords">{{ old('meta_keywords', $post->meta_keywords) }}</textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="name">Meta Description </label>

                        <div class="editor">
                            <textarea class="form-control  translation-field" name="meta_description" id="meta_description" rows="6"
                                      placeholder="Meta Description">{{ old('meta_description', $post->meta_description) }}</textarea>
                        </div>
                    </div>

                </div>
            </div>

        </div>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">{{ $post->exists ? 'Save' : 'Create' }}</button>
        </div>


    </form>

    {{--Tier Source, Its not visible on the page rather its used to add more date fiels into the dates section--}}
    <div id="custom-field-tier-source" class="tier-source">
        @include('cms.blog._tier', ['key' => '{tierId}'])
    </div>


@endsection

resources/views/cms/blog/index.blade.php
@extends('cms.layouts.default')

@section('title', 'Blog Posts')


@section('heading')

    <div class="row heading">
        <div class="col-md-10">
            <h3>@yield('title')</h3>
        </div>
        <div class="col-md-2 text-right">
            <a href="{{ route('cms.blog.create') }}" class="btn btn-primary">Create New Post</a>
        </div>
    </div>

@stop

@section('content')

    <table class="table table-hover" data-table="table" id="record-list">
        <thead>
        <tr>
            <th>Name</th>
            <th>Title</th>
            <th width="150">Published</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
            @forelse($posts as $post)
                <tr>
                    <td>
                        <a href="{{ route('cms.blog.edit', $post->id) }}">
                        {{ $post->name }}
                        </a>
                    </td>
                    <td>
                        {{ $post->title }}
                    </td>
                    <td>{{ $post->published_at->diffForHumans() }}</td>
                    <td class="actions">
                        <a href="{{ route('cms.blog.edit', $post->id) }}">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                        <a href="{{ route('cms.blog.destroy', $post->id) }}" class="confirm-action">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                        <a href="{{ route('cms.mediable.show', ['blog', $post->id]) }}">
                            <span class="glyphicon glyphicon-file"></span>
                        </a>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" align="center">There are no posts.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
@endsection